image:
  tag: 8.5.5
extraEnv:
  AWS_REGION: {{region_name}}
  AWS_DEFAULT_REGION: {{region_name}}
serviceAccount:
  create: false
  name: external-secrets-controller
# securityContext:
#   fsGroup: 65534
