# image:
#   tag: v1beta2-1.2.3-3.1.1
spark:
  jobNamespaces: []
  serviceAccount:
    create: false
controller:    
  serviceAccount:
    create: true  
metrics:
  enable: false
webhook:
  enable: true
  port: 443
